import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextUIProviders from "./nextui-provider";
import Header from "@/components/header";
import SessionProviders from "./session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-6xl h-screen">
          <SessionProviders>
            <NextUIProviders>
              <Header />
              {children}
            </NextUIProviders>
          </SessionProviders>
        </div>
      </body>
    </html>
  );
}
